// Tipos para eventos IoT eléctricos

export interface DeviceConnectionStatus {
  deviceId: string;
  status: "connected" | "disconnected" | "reconnecting";
  lastSeen?: Date;
  metadata?: {
    signalStrength?: number;
    batteryLevel?: number;
    firmwareVersion?: string;
    location?: string;
  };
}

export interface VoltageReading {
  deviceId: string;
  voltage: number;
  phase?: "L1" | "L2" | "L3" | "N";
  quality: "good" | "warning" | "critical";
  location?: string;
  frequency?: number;
  harmonics?: number;
}

export interface CurrentReading {
  deviceId: string;
  current: number;
  phase?: "L1" | "L2" | "L3" | "N";
  powerFactor?: number;
  location?: string;
  rms?: number;
  peak?: number;
}

export interface PowerConsumption {
  deviceId: string;
  activePower: number; // Potencia activa (W)
  reactivePower?: number; // Potencia reactiva (VAR)
  apparentPower?: number; // Potencia aparente (VA)
  energy: number; // Energía acumulada (kWh)
  cost?: number; // Costo estimado
  location?: string;
  tariff?: string;
}

export interface DeviceReconnection {
  deviceId: string;
  previousStatus: string;
  reconnectionTime: number; // Tiempo en ms
  attempts: number;
  success: boolean;
  reason?: string;
  method?: "auto" | "manual";
}

export interface PowerOutageAlert {
  deviceId: string;
  location: string;
  affectedDevices?: string[];
  estimatedDuration?: number; // en minutos
  cause?: "planned" | "unplanned" | "maintenance";
  priority: "low" | "medium" | "high" | "critical";
}

export interface VoltageAnomalyAlert {
  deviceId: string;
  currentVoltage: number;
  expectedVoltage: number;
  deviation: number; // Porcentaje de desviación
  phase?: string;
  duration?: number; // Duración de la anomalía en segundos
  trend?: "increasing" | "decreasing" | "stable";
}

export interface SwitchState {
  deviceId: string;
  switchId: string;
  state: "on" | "off" | "auto" | "fault";
  controlledBy?: string;
  reason?: string;
  timestamp?: Date;
  remoteControl?: boolean;
}

export interface EmergencyStop {
  deviceId: string;
  reason: string;
  triggeredBy: string;
  affectedSystems: string[];
  location?: string;
  recoveryProcedure?: string;
  estimatedDowntime?: number;
}

export interface IoTAlert {
  id: string;
  type: "error" | "warning" | "info" | "success";
  title: string;
  message: string;
  deviceId: string;
  severity: "low" | "medium" | "high" | "critical";
  timestamp: string;
  source?: string;
  autoGenerated: boolean;
  acknowledged?: boolean;
  resolvedAt?: string;
  metadata?: Record<string, any>;
}

export interface PowerStatistics {
  deviceId: string;
  activePower: number;
  energy: number;
  cost?: number;
  timestamp: string;
  trend: "up" | "down" | "stable";
  efficiency?: number;
  carbonFootprint?: number;
}

export interface DeviceThresholds {
  voltage: {
    min: number;
    max: number;
    nominal: number;
  };
  current: {
    max: number;
    warning: number;
  };
  power: {
    max: number;
    warning: number;
  };
  temperature?: {
    max: number;
    warning: number;
  };
}

export interface IoTEventData {
  timestamp: string;
  source?: string;
  eventType: string;
  deviceId: string;
  metadata?: Record<string, any>;
}

// Tipos para respuestas de la API
export interface IoTApiResponse<T = any> {
  success: boolean;
  data?: T;
  message?: string;
  timestamp: string;
}

// Tipos para configuración de dispositivos
export interface DeviceConfiguration {
  deviceId: string;
  thresholds: DeviceThresholds;
  alertsEnabled: boolean;
  reportingInterval: number; // en segundos
  location?: string;
  description?: string;
  maintenanceSchedule?: {
    lastMaintenance?: Date;
    nextMaintenance?: Date;
    interval: number; // en días
  };
}

// Tipos para métricas en tiempo real
export interface RealTimeMetrics {
  totalDevices: number;
  activeDevices: number;
  offlineDevices: number;
  totalPowerConsumption: number;
  totalEnergyCost: number;
  activeAlerts: number;
  criticalAlerts: number;
  lastUpdate: string;
}

// Tipos para eventos del WebSocket
export type IoTWebSocketEvents = {
  // Eventos de dispositivos
  "device:connection_status": DeviceConnectionStatus;
  "device:voltage_reading": VoltageReading;
  "device:current_reading": CurrentReading;
  "device:power_consumption": PowerConsumption;
  "device:reconnection": DeviceReconnection;

  // Eventos de alertas
  "alert:power_outage": PowerOutageAlert;
  "alert:voltage_anomaly": VoltageAnomalyAlert;
  "alert:overcurrent": {
    deviceId: string;
    current: number;
    maxAllowed: number;
  };
  "alert:critical": IoTAlert;
  "alert:emergency": EmergencyStop;

  // Eventos de control
  "control:switch_state": SwitchState;
  "control:emergency_stop": EmergencyStop;

  // Eventos de estadísticas
  "stats:power_update": PowerStatistics;
  "stats:realtime_metrics": RealTimeMetrics;

  // Eventos de respuesta
  "device:connection_update": IoTEventData & DeviceConnectionStatus;
  "device:voltage_update": IoTEventData & VoltageReading;
  "device:current_update": IoTEventData & CurrentReading;
  "device:power_update": IoTEventData & PowerConsumption;
  "device:reconnection_update": IoTEventData & DeviceReconnection;
  "control:switch_update": IoTEventData & SwitchState;
};
